version: '3.8'

services:
  f1-fan-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: f1-fan-bot
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - DATABASE_PATH=/app/data/f1bot.db
      - NODE_ENV=${NODE_ENV:-production}
    volumes:
      - ./data:/app/data
    networks:
      - f1-network

networks:
  f1-network:
    driver: bridge 